# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-05-02 22:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Casa',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255)),
                ('ciudad', models.CharField(max_length=255)),
                ('direccion', models.CharField(max_length=255)),
                ('descripcion', models.CharField(max_length=255)),
                ('publico', models.BooleanField()),
                ('imagen', models.ImageField(blank=True, upload_to=b'')),
            ],
            options={
                'ordering': ('id',),
            },
        ),
    ]
