# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-05-17 22:52
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('casas', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='oferta',
            name='casaOfertada',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='oferta', to='casas.Casa'),
        ),
    ]
