# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-05-03 08:53
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('casas', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='casa',
            name='date',
            field=models.DateField(blank=True, default=datetime.date.today),
        ),
        migrations.AddField(
            model_name='casa',
            name='numeroBanios',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='casa',
            name='numeroHabitaciones',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='casa',
            name='wifi',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='casa',
            name='publico',
            field=models.BooleanField(default=False),
        ),
    ]
