# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-05-03 09:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('casas', '0002_auto_20160503_0853'),
    ]

    operations = [
        migrations.AddField(
            model_name='casa',
            name='latitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='casa',
            name='longitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='casa',
            name='parking',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='casa',
            name='postcode',
            field=models.CharField(blank=True, max_length=15),
        ),
        migrations.AlterField(
            model_name='casa',
            name='descripcion',
            field=models.CharField(max_length=2555),
        ),
    ]
