# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-05-06 11:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('casas', '0004_perfil'),
    ]

    operations = [
        migrations.RenameField(
            model_name='casa',
            old_name='date',
            new_name='fecha',
        ),
        migrations.AddField(
            model_name='casa',
            name='mascotas',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='casa',
            name='piscina',
            field=models.BooleanField(default=False),
        ),
    ]
