# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-05-08 22:23
from __future__ import unicode_literals

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('casas', '0007_auto_20160508_2038'),
    ]

    operations = [
        migrations.CreateModel(
            name='Favorito',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fechaCreado', models.DateField(default=datetime.date.today)),
                ('casaFavorito', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='casas.Casa')),
                ('usuarioFavorito', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('id',),
            },
        ),
        migrations.CreateModel(
            name='Imagenes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagen', models.ImageField(blank=True, upload_to=b'')),
            ],
        ),
        migrations.CreateModel(
            name='Oferta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fechaInicio', models.DateField()),
                ('fechaFin', models.DateField()),
                ('fechaCreada', models.DateField(default=datetime.date.today)),
                ('precio', models.FloatField(null=True)),
                ('casaOfertada', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='casas.Casa')),
            ],
            options={
                'ordering': ('id', 'precio'),
            },
        ),
    ]
