# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-05-08 22:29
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('casas', '0008_favorito_imagenes_oferta'),
    ]

    operations = [
        migrations.AddField(
            model_name='imagenes',
            name='casaImagen',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='casas.Casa'),
            preserve_default=False,
        ),
    ]
