# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-05-08 22:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='perfil',
            name='facebookAccount',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='perfil',
            name='twitterAccount',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='perfil',
            name='website',
            field=models.URLField(blank=True),
        ),
    ]
